### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by cainytheslave**
I took some time to give your code a bit of refactoring, you don't necessarily need to merge/adopt my design but maybe you can look through it and pick up some knowledge!

### CODE REVIEW

**Comment by NielsNL1** [comment]
Wow that's really kind of you, I wanted to do this to but i was strugeling with this, Thank you!

**Comment by NielsNL1** [comment]
what did i just press what is a self-requested review

**Review by NielsNL1 — APPROVED** [review]

**Review by NielsNL1 — APPROVED** [review]

**Review by NielsNL1 — APPROVED** [review]

**Review by NielsNL1 — APPROVED** [review]

**Review by NielsNL1 — APPROVED** [review]

**Comment by NielsNL1** [comment]
How do merge you design? I am not really familair with github.

**Comment by cainytheslave** [comment]
Hi Niels, I resolved the merge conflicts so you can now merge to master. I did this by editing the merge conflicts in the index.html file, so I kept for example your favicon but also kept my refactored code.

**Comment by NielsNL1** [comment]
Oh thats what i had to do, Thank you! so i just press the big green button called 'Merge pull request' now?

**Pull request merged**
